components:
  schemas:
    Pets:
      type: object
      properties:
        name:
          type: string
          description: Nombre de la mascota
        specie:
          type: string
          description: Especie de la mascota
        birthDate:
          type: date
          description: Fecha de nacimiento estimada de la mascota
        adopted:
          type: boolean
          description: Fue adoptado ya?
        owner:
          type: string
          description: ObjectId de referencia del usuario dueño de la mascota
        image:
          type: string
          description: Foto de la mascota
      example:
        name: Rufus
        specie: Labrador
        birthDate: 12-30-2000
        adopted: true
        owner: 650b6a88674d074e1dca8c12
        image: https://assets.stickpng.com/images/580b57fbd9996e24bc43bbdc.png
  responses:
    createSuccess:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        payload:
          type: object
          description: Objeto con los datos de la mascota ingresada
      example:
        status: success
        payload:
          name: Rufus
          specie: Labrador
          birthDate: 2000-12-30
          adopted": false
          image: https://assets.stickpng.com/images/580b57fbd9996e24bc43bbdc.png
          _id: 653bc489806d3d93518d1ea8
          _v: 0
    clientError:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        error:
          type: string
          description: Descripción del error
      example:
        status: error
        description: Incomplete values
    serverError:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        error:
          type: string
          description: Descripción del error
      example:
        status: fatal
        description: Server error
    readSuccess:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        payload:
          type: array
          description: Lista de mascotas
      example:
        status: success
        payload:
          - name: Rufus
            specie: Labrador
            birthDate: 2000-12-30
            adopted": false
            image: https://assets.stickpng.com/images/580b57fbd9996e24bc43bbdc.png
            _id: 653bc489806d3d93518d1ea8
            _v: 0
          - name: Nolink
            specie: Salchicha
            birthDate: 2000-12-30
            adopted": false
            image: https://img.pikbest.com/origin/09/19/03/389pIkbEsT3kc.png!w700wp
            _id: 653bc489806d3d93518d1dc9
            _v: 0
    notFound:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        error:
          type: string
          description: Descripción del error
      example:
        status: success
        error: Not found
paths:
  /api/pets:
    post:
      summary: Crear una nueva mascota en la base de datos
      tags:
        - Pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Pets'
      responses:
        "201":
          description: Éxito en la creación de una mascota
          content:
            application/json:
              schema:
                $ref: '#components/responses/createSuccess'
        "400":
          description: Fracaso en la creación de una mascota
          content:
            application/json:
              schema:
                $ref: '#components/responses/clientError'
        "500":
          description: FATAL - Servidor caído
          content:
            application/json:
              schema:
                $ref: '#components/responses/serverError'
    get:
      summary: Leer todos las mascotas de la base de datos (paginados)
      tags:
        - Pets
      responses:
        "200":
          description: Éxito en la lectura de mascotas
          content:
            application/json:
              schema:
                $ref: '#components/responses/readSuccess'
        "404":
          description: Recurso no encontrado
          content:
            application/json:
              schema:
                $ref: '#components/responses/notFound'
        "500":
          description: FATAL - Servidor caído
          content:
            application/json:
              schema:
                $ref: '#components/responses/serverError'