apiVersion: v1
kind: Service
metadata:
  name: faker-service
spec:
  selector:
    app: fakerusers
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faker-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fakerusers
  template:
    metadata:
      labels:
        app: fakerusers
    spec:
      containers:
        - name: faker-container
          image: ignacioborraz/fakerusers:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always